server.port=8005

spring.jpa.hibernate.ddl-auto = update 

spring.datasource.url=jdbc:mysql://localhost:3306/medicare_database

 spring.datasource.username=root

 spring.datasource.password=swapnil2908

 spring.jpa.show-sql=true
 
 
 jwt.secret=8Sbnx589zh6g9d66gda8u5ysxhb12452dsgagfdw75csssd4